-- ═══════════════════════════════════════════════════════════════
--  T42 · the 42-day plan
--  Run after 21-t42-seed.sql.
--
--  72 sessions across three tracks. A day with NO row here is a rest day:
--  the absence is the meaning, so there is nothing to seed for one and the
--  app reads a missing row as rest rather than as a gap.
--
--    START      3 sessions a week  (days 1, 3, 5)
--    TRANSFORM  4 sessions a week  (days 1, 2, 4, 6)
--    PERFORM    5 sessions a week  (days 1, 2, 3, 5, 6)
--
--  Every exercise name here resolves against the 310 in the HITFAT+
--  library, checked when this file was generated. That matters more than it
--  looks: the app drops a name it cannot find rather than substituting one,
--  because the player's own fallback would show someone a squat where the
--  plan said plank and give them no way to know.
--
--  Volume climbs across the six weeks — a round is added from week 3 and
--  reps rise from week 5. The brief's arc (RESET, BUILD, PROGRESS, PUSH,
--  BREAKTHROUGH, FINISH STRONG) is in t42_weeks; this is what it means in
--  sets and reps.
--
--  Everything is bodyweight or one bottle. A 42-day challenge has to be
--  doable in a bedroom on day one or it loses the people it is most for.
-- ═══════════════════════════════════════════════════════════════

insert into public.t42_plan_days
  (challenge_id, track, day_no, title, exercises, est_minutes, level, equipment, focus)
select c.id, v.track, v.day_no, v.title, v.exercises, v.est_minutes, v.level, v.equipment, v.focus
  from public.t42_challenges c
  cross join (values
    ('start',1,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":3,"reps":12},{"n":"Incline Push Up (Chair)","sets":3,"reps":10},{"n":"Reverse Lunges","sets":3,"reps":10},{"n":"Dead Bug","sets":3,"reps":12},{"n":"Plank","sets":3,"reps":30}]'::jsonb,25,'Beginner','None','Learn the five patterns. Nothing to failure.'),
    ('start',3,'MOVE & BREATHE','[{"n":"Jumping Jack","sets":3,"reps":30},{"n":"Chair Squat","sets":3,"reps":12},{"n":"Wall Push Up","sets":3,"reps":12},{"n":"Bird Dog","sets":3,"reps":10},{"n":"Side Plank","sets":2,"reps":25}]'::jsonb,25,'Beginner','None','Get the heart up without wrecking tomorrow.'),
    ('start',5,'LOWER & CORE','[{"n":"Bodyweight Squat","sets":3,"reps":15},{"n":"Hip Thrust","sets":3,"reps":15},{"n":"Walking Lunges","sets":3,"reps":12},{"n":"Crunch","sets":3,"reps":15},{"n":"Plank","sets":3,"reps":35}]'::jsonb,25,'Beginner','None','Legs and midline. Slow and controlled.'),
    ('start',8,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":3,"reps":12},{"n":"Incline Push Up (Chair)","sets":3,"reps":10},{"n":"Reverse Lunges","sets":3,"reps":10},{"n":"Dead Bug","sets":3,"reps":12},{"n":"Plank","sets":3,"reps":30}]'::jsonb,25,'Beginner','None','Learn the five patterns. Nothing to failure.'),
    ('start',10,'MOVE & BREATHE','[{"n":"Jumping Jack","sets":3,"reps":30},{"n":"Chair Squat","sets":3,"reps":12},{"n":"Wall Push Up","sets":3,"reps":12},{"n":"Bird Dog","sets":3,"reps":10},{"n":"Side Plank","sets":2,"reps":25}]'::jsonb,25,'Beginner','None','Get the heart up without wrecking tomorrow.'),
    ('start',12,'LOWER & CORE','[{"n":"Bodyweight Squat","sets":3,"reps":15},{"n":"Hip Thrust","sets":3,"reps":15},{"n":"Walking Lunges","sets":3,"reps":12},{"n":"Crunch","sets":3,"reps":15},{"n":"Plank","sets":3,"reps":35}]'::jsonb,25,'Beginner','None','Legs and midline. Slow and controlled.'),
    ('start',15,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":4,"reps":12},{"n":"Incline Push Up (Chair)","sets":4,"reps":10},{"n":"Reverse Lunges","sets":4,"reps":10},{"n":"Dead Bug","sets":4,"reps":12},{"n":"Plank","sets":4,"reps":30}]'::jsonb,30,'Beginner','None','Learn the five patterns. Nothing to failure.'),
    ('start',17,'MOVE & BREATHE','[{"n":"Jumping Jack","sets":4,"reps":30},{"n":"Chair Squat","sets":4,"reps":12},{"n":"Wall Push Up","sets":4,"reps":12},{"n":"Bird Dog","sets":4,"reps":10},{"n":"Side Plank","sets":3,"reps":25}]'::jsonb,30,'Beginner','None','Get the heart up without wrecking tomorrow.'),
    ('start',19,'LOWER & CORE','[{"n":"Bodyweight Squat","sets":4,"reps":15},{"n":"Hip Thrust","sets":4,"reps":15},{"n":"Walking Lunges","sets":4,"reps":12},{"n":"Crunch","sets":4,"reps":15},{"n":"Plank","sets":4,"reps":35}]'::jsonb,30,'Beginner','None','Legs and midline. Slow and controlled.'),
    ('start',22,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":4,"reps":12},{"n":"Incline Push Up (Chair)","sets":4,"reps":10},{"n":"Reverse Lunges","sets":4,"reps":10},{"n":"Dead Bug","sets":4,"reps":12},{"n":"Plank","sets":4,"reps":30}]'::jsonb,30,'Beginner','None','Learn the five patterns. Nothing to failure.'),
    ('start',24,'MOVE & BREATHE','[{"n":"Jumping Jack","sets":4,"reps":30},{"n":"Chair Squat","sets":4,"reps":12},{"n":"Wall Push Up","sets":4,"reps":12},{"n":"Bird Dog","sets":4,"reps":10},{"n":"Side Plank","sets":3,"reps":25}]'::jsonb,30,'Beginner','None','Get the heart up without wrecking tomorrow.'),
    ('start',26,'LOWER & CORE','[{"n":"Bodyweight Squat","sets":4,"reps":15},{"n":"Hip Thrust","sets":4,"reps":15},{"n":"Walking Lunges","sets":4,"reps":12},{"n":"Crunch","sets":4,"reps":15},{"n":"Plank","sets":4,"reps":35}]'::jsonb,30,'Beginner','None','Legs and midline. Slow and controlled.'),
    ('start',29,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":4,"reps":14},{"n":"Incline Push Up (Chair)","sets":4,"reps":12},{"n":"Reverse Lunges","sets":4,"reps":12},{"n":"Dead Bug","sets":4,"reps":14},{"n":"Plank","sets":4,"reps":34}]'::jsonb,30,'Beginner','None','Learn the five patterns. Nothing to failure.'),
    ('start',31,'MOVE & BREATHE','[{"n":"Jumping Jack","sets":4,"reps":34},{"n":"Chair Squat","sets":4,"reps":14},{"n":"Wall Push Up","sets":4,"reps":14},{"n":"Bird Dog","sets":4,"reps":12},{"n":"Side Plank","sets":3,"reps":29}]'::jsonb,30,'Beginner','None','Get the heart up without wrecking tomorrow.'),
    ('start',33,'LOWER & CORE','[{"n":"Bodyweight Squat","sets":4,"reps":17},{"n":"Hip Thrust","sets":4,"reps":17},{"n":"Walking Lunges","sets":4,"reps":14},{"n":"Crunch","sets":4,"reps":17},{"n":"Plank","sets":4,"reps":40}]'::jsonb,30,'Beginner','None','Legs and midline. Slow and controlled.'),
    ('start',36,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":4,"reps":14},{"n":"Incline Push Up (Chair)","sets":4,"reps":12},{"n":"Reverse Lunges","sets":4,"reps":12},{"n":"Dead Bug","sets":4,"reps":14},{"n":"Plank","sets":4,"reps":34}]'::jsonb,30,'Beginner','None','Learn the five patterns. Nothing to failure.'),
    ('start',38,'MOVE & BREATHE','[{"n":"Jumping Jack","sets":4,"reps":34},{"n":"Chair Squat","sets":4,"reps":14},{"n":"Wall Push Up","sets":4,"reps":14},{"n":"Bird Dog","sets":4,"reps":12},{"n":"Side Plank","sets":3,"reps":29}]'::jsonb,30,'Beginner','None','Get the heart up without wrecking tomorrow.'),
    ('start',40,'LOWER & CORE','[{"n":"Bodyweight Squat","sets":4,"reps":17},{"n":"Hip Thrust","sets":4,"reps":17},{"n":"Walking Lunges","sets":4,"reps":14},{"n":"Crunch","sets":4,"reps":17},{"n":"Plank","sets":4,"reps":40}]'::jsonb,30,'Beginner','None','Legs and midline. Slow and controlled.'),
    ('transform',1,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":3,"reps":15},{"n":"Push Up","sets":3,"reps":12},{"n":"Reverse Lunges","sets":3,"reps":12},{"n":"Bottle Bent Over Row","sets":3,"reps":12},{"n":"Plank","sets":3,"reps":45}]'::jsonb,35,'Intermediate','Dumbbell (optional)','Everything, once. Set the baseline for the six weeks.'),
    ('transform',2,'BURN · CONDITIONING','[{"n":"Jumping Jack","sets":4,"reps":40},{"n":"Squat Jump","sets":4,"reps":12},{"n":"Mountain Climber","sets":4,"reps":30},{"n":"Half Burpee","sets":4,"reps":10},{"n":"High Knee","sets":4,"reps":30}]'::jsonb,35,'Intermediate','None','Keep moving. Short rests, honest effort.'),
    ('transform',4,'UPPER & CORE','[{"n":"Push Up","sets":4,"reps":12},{"n":"Diamond Push Up","sets":3,"reps":10},{"n":"Bottle Shoulder Press","sets":3,"reps":12},{"n":"Bottle Bent Over Row","sets":3,"reps":12},{"n":"Russian Twist","sets":3,"reps":20},{"n":"Hollow Hold","sets":3,"reps":30}]'::jsonb,35,'Intermediate','None','Push, pull, brace.'),
    ('transform',6,'LOWER BODY','[{"n":"Bodyweight Squat","sets":4,"reps":15},{"n":"Walking Lunges","sets":3,"reps":14},{"n":"Bulgarian Split Squat","sets":3,"reps":10},{"n":"Hip Thrust","sets":3,"reps":18},{"n":"Calf Raises","sets":3,"reps":20},{"n":"Wall Sit","sets":3,"reps":40}]'::jsonb,35,'Intermediate','None','The biggest muscles, the biggest burn.'),
    ('transform',8,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":3,"reps":15},{"n":"Push Up","sets":3,"reps":12},{"n":"Reverse Lunges","sets":3,"reps":12},{"n":"Bottle Bent Over Row","sets":3,"reps":12},{"n":"Plank","sets":3,"reps":45}]'::jsonb,35,'Intermediate','Dumbbell (optional)','Everything, once. Set the baseline for the six weeks.'),
    ('transform',9,'BURN · CONDITIONING','[{"n":"Jumping Jack","sets":4,"reps":40},{"n":"Squat Jump","sets":4,"reps":12},{"n":"Mountain Climber","sets":4,"reps":30},{"n":"Half Burpee","sets":4,"reps":10},{"n":"High Knee","sets":4,"reps":30}]'::jsonb,35,'Intermediate','None','Keep moving. Short rests, honest effort.'),
    ('transform',11,'UPPER & CORE','[{"n":"Push Up","sets":4,"reps":12},{"n":"Diamond Push Up","sets":3,"reps":10},{"n":"Bottle Shoulder Press","sets":3,"reps":12},{"n":"Bottle Bent Over Row","sets":3,"reps":12},{"n":"Russian Twist","sets":3,"reps":20},{"n":"Hollow Hold","sets":3,"reps":30}]'::jsonb,35,'Intermediate','None','Push, pull, brace.'),
    ('transform',13,'LOWER BODY','[{"n":"Bodyweight Squat","sets":4,"reps":15},{"n":"Walking Lunges","sets":3,"reps":14},{"n":"Bulgarian Split Squat","sets":3,"reps":10},{"n":"Hip Thrust","sets":3,"reps":18},{"n":"Calf Raises","sets":3,"reps":20},{"n":"Wall Sit","sets":3,"reps":40}]'::jsonb,35,'Intermediate','None','The biggest muscles, the biggest burn.'),
    ('transform',15,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":4,"reps":15},{"n":"Push Up","sets":4,"reps":12},{"n":"Reverse Lunges","sets":4,"reps":12},{"n":"Bottle Bent Over Row","sets":4,"reps":12},{"n":"Plank","sets":4,"reps":45}]'::jsonb,40,'Intermediate','Dumbbell (optional)','Everything, once. Set the baseline for the six weeks.'),
    ('transform',16,'BURN · CONDITIONING','[{"n":"Jumping Jack","sets":5,"reps":40},{"n":"Squat Jump","sets":5,"reps":12},{"n":"Mountain Climber","sets":5,"reps":30},{"n":"Half Burpee","sets":5,"reps":10},{"n":"High Knee","sets":5,"reps":30}]'::jsonb,40,'Intermediate','None','Keep moving. Short rests, honest effort.'),
    ('transform',18,'UPPER & CORE','[{"n":"Push Up","sets":5,"reps":12},{"n":"Diamond Push Up","sets":4,"reps":10},{"n":"Bottle Shoulder Press","sets":4,"reps":12},{"n":"Bottle Bent Over Row","sets":4,"reps":12},{"n":"Russian Twist","sets":4,"reps":20},{"n":"Hollow Hold","sets":4,"reps":30}]'::jsonb,40,'Intermediate','None','Push, pull, brace.'),
    ('transform',20,'LOWER BODY','[{"n":"Bodyweight Squat","sets":5,"reps":15},{"n":"Walking Lunges","sets":4,"reps":14},{"n":"Bulgarian Split Squat","sets":4,"reps":10},{"n":"Hip Thrust","sets":4,"reps":18},{"n":"Calf Raises","sets":4,"reps":20},{"n":"Wall Sit","sets":4,"reps":40}]'::jsonb,40,'Intermediate','None','The biggest muscles, the biggest burn.'),
    ('transform',22,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":4,"reps":15},{"n":"Push Up","sets":4,"reps":12},{"n":"Reverse Lunges","sets":4,"reps":12},{"n":"Bottle Bent Over Row","sets":4,"reps":12},{"n":"Plank","sets":4,"reps":45}]'::jsonb,40,'Intermediate','Dumbbell (optional)','Everything, once. Set the baseline for the six weeks.'),
    ('transform',23,'BURN · CONDITIONING','[{"n":"Jumping Jack","sets":5,"reps":40},{"n":"Squat Jump","sets":5,"reps":12},{"n":"Mountain Climber","sets":5,"reps":30},{"n":"Half Burpee","sets":5,"reps":10},{"n":"High Knee","sets":5,"reps":30}]'::jsonb,40,'Intermediate','None','Keep moving. Short rests, honest effort.'),
    ('transform',25,'UPPER & CORE','[{"n":"Push Up","sets":5,"reps":12},{"n":"Diamond Push Up","sets":4,"reps":10},{"n":"Bottle Shoulder Press","sets":4,"reps":12},{"n":"Bottle Bent Over Row","sets":4,"reps":12},{"n":"Russian Twist","sets":4,"reps":20},{"n":"Hollow Hold","sets":4,"reps":30}]'::jsonb,40,'Intermediate','None','Push, pull, brace.'),
    ('transform',27,'LOWER BODY','[{"n":"Bodyweight Squat","sets":5,"reps":15},{"n":"Walking Lunges","sets":4,"reps":14},{"n":"Bulgarian Split Squat","sets":4,"reps":10},{"n":"Hip Thrust","sets":4,"reps":18},{"n":"Calf Raises","sets":4,"reps":20},{"n":"Wall Sit","sets":4,"reps":40}]'::jsonb,40,'Intermediate','None','The biggest muscles, the biggest burn.'),
    ('transform',29,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":4,"reps":17},{"n":"Push Up","sets":4,"reps":14},{"n":"Reverse Lunges","sets":4,"reps":14},{"n":"Bottle Bent Over Row","sets":4,"reps":14},{"n":"Plank","sets":4,"reps":52}]'::jsonb,40,'Intermediate','Dumbbell (optional)','Everything, once. Set the baseline for the six weeks.'),
    ('transform',30,'BURN · CONDITIONING','[{"n":"Jumping Jack","sets":5,"reps":46},{"n":"Squat Jump","sets":5,"reps":14},{"n":"Mountain Climber","sets":5,"reps":34},{"n":"Half Burpee","sets":5,"reps":12},{"n":"High Knee","sets":5,"reps":34}]'::jsonb,40,'Intermediate','None','Keep moving. Short rests, honest effort.'),
    ('transform',32,'UPPER & CORE','[{"n":"Push Up","sets":5,"reps":14},{"n":"Diamond Push Up","sets":4,"reps":12},{"n":"Bottle Shoulder Press","sets":4,"reps":14},{"n":"Bottle Bent Over Row","sets":4,"reps":14},{"n":"Russian Twist","sets":4,"reps":23},{"n":"Hollow Hold","sets":4,"reps":34}]'::jsonb,40,'Intermediate','None','Push, pull, brace.'),
    ('transform',34,'LOWER BODY','[{"n":"Bodyweight Squat","sets":5,"reps":17},{"n":"Walking Lunges","sets":4,"reps":16},{"n":"Bulgarian Split Squat","sets":4,"reps":12},{"n":"Hip Thrust","sets":4,"reps":21},{"n":"Calf Raises","sets":4,"reps":23},{"n":"Wall Sit","sets":4,"reps":46}]'::jsonb,40,'Intermediate','None','The biggest muscles, the biggest burn.'),
    ('transform',36,'FULL BODY 01','[{"n":"Bodyweight Squat","sets":4,"reps":17},{"n":"Push Up","sets":4,"reps":14},{"n":"Reverse Lunges","sets":4,"reps":14},{"n":"Bottle Bent Over Row","sets":4,"reps":14},{"n":"Plank","sets":4,"reps":52}]'::jsonb,40,'Intermediate','Dumbbell (optional)','Everything, once. Set the baseline for the six weeks.'),
    ('transform',37,'BURN · CONDITIONING','[{"n":"Jumping Jack","sets":5,"reps":46},{"n":"Squat Jump","sets":5,"reps":14},{"n":"Mountain Climber","sets":5,"reps":34},{"n":"Half Burpee","sets":5,"reps":12},{"n":"High Knee","sets":5,"reps":34}]'::jsonb,40,'Intermediate','None','Keep moving. Short rests, honest effort.'),
    ('transform',39,'UPPER & CORE','[{"n":"Push Up","sets":5,"reps":14},{"n":"Diamond Push Up","sets":4,"reps":12},{"n":"Bottle Shoulder Press","sets":4,"reps":14},{"n":"Bottle Bent Over Row","sets":4,"reps":14},{"n":"Russian Twist","sets":4,"reps":23},{"n":"Hollow Hold","sets":4,"reps":34}]'::jsonb,40,'Intermediate','None','Push, pull, brace.'),
    ('transform',41,'LOWER BODY','[{"n":"Bodyweight Squat","sets":5,"reps":17},{"n":"Walking Lunges","sets":4,"reps":16},{"n":"Bulgarian Split Squat","sets":4,"reps":12},{"n":"Hip Thrust","sets":4,"reps":21},{"n":"Calf Raises","sets":4,"reps":23},{"n":"Wall Sit","sets":4,"reps":46}]'::jsonb,40,'Intermediate','None','The biggest muscles, the biggest burn.'),
    ('perform',1,'FULL BODY POWER','[{"n":"Squat Jump","sets":4,"reps":15},{"n":"Explosive Push Up","sets":4,"reps":10},{"n":"Bulgarian Split Squat","sets":4,"reps":12},{"n":"Bottle Bent Over Row","sets":4,"reps":14},{"n":"Plank Shoulder Taps","sets":3,"reps":24},{"n":"Hollow Hold","sets":3,"reps":45}]'::jsonb,45,'Advanced','Dumbbell (optional)','Move well, move fast, then move heavy.'),
    ('perform',2,'ENGINE','[{"n":"Burpee","sets":5,"reps":12},{"n":"Sprint On Spot","sets":5,"reps":30},{"n":"Mountain Climber","sets":5,"reps":40},{"n":"Tuck Jump","sets":4,"reps":12},{"n":"Skater Jump","sets":4,"reps":20}]'::jsonb,45,'Advanced','None','Conditioning. This one is supposed to hurt.'),
    ('perform',3,'PUSH & PULL','[{"n":"Push Up","sets":5,"reps":15},{"n":"Diamond Push Up","sets":4,"reps":12},{"n":"Decline Push Up","sets":4,"reps":12},{"n":"Bottle Bent Over Row","sets":4,"reps":15},{"n":"Bottle Shoulder Press","sets":4,"reps":12},{"n":"Tricep Dip Chair","sets":4,"reps":12}]'::jsonb,45,'Advanced','None','Upper body volume.'),
    ('perform',5,'LEGS & LUNGS','[{"n":"Bodyweight Squat","sets":5,"reps":20},{"n":"Lunges Jump","sets":4,"reps":16},{"n":"Broad Jump","sets":4,"reps":10},{"n":"Single Leg Glutes Bridge","sets":3,"reps":15},{"n":"Wall Sit","sets":3,"reps":60},{"n":"Calf Raises","sets":4,"reps":25}]'::jsonb,45,'Advanced','None','Strength endurance in the legs.'),
    ('perform',6,'CORE & CARRY','[{"n":"Hollow Hold","sets":4,"reps":45},{"n":"Bicycle Crunch","sets":4,"reps":30},{"n":"Leg Raises","sets":4,"reps":15},{"n":"Bear Walk","sets":4,"reps":20},{"n":"Side Plank","sets":3,"reps":40},{"n":"Plank","sets":3,"reps":60}]'::jsonb,45,'Advanced','None','A midline that holds under fatigue.'),
    ('perform',8,'FULL BODY POWER','[{"n":"Squat Jump","sets":4,"reps":15},{"n":"Explosive Push Up","sets":4,"reps":10},{"n":"Bulgarian Split Squat","sets":4,"reps":12},{"n":"Bottle Bent Over Row","sets":4,"reps":14},{"n":"Plank Shoulder Taps","sets":3,"reps":24},{"n":"Hollow Hold","sets":3,"reps":45}]'::jsonb,45,'Advanced','Dumbbell (optional)','Move well, move fast, then move heavy.'),
    ('perform',9,'ENGINE','[{"n":"Burpee","sets":5,"reps":12},{"n":"Sprint On Spot","sets":5,"reps":30},{"n":"Mountain Climber","sets":5,"reps":40},{"n":"Tuck Jump","sets":4,"reps":12},{"n":"Skater Jump","sets":4,"reps":20}]'::jsonb,45,'Advanced','None','Conditioning. This one is supposed to hurt.'),
    ('perform',10,'PUSH & PULL','[{"n":"Push Up","sets":5,"reps":15},{"n":"Diamond Push Up","sets":4,"reps":12},{"n":"Decline Push Up","sets":4,"reps":12},{"n":"Bottle Bent Over Row","sets":4,"reps":15},{"n":"Bottle Shoulder Press","sets":4,"reps":12},{"n":"Tricep Dip Chair","sets":4,"reps":12}]'::jsonb,45,'Advanced','None','Upper body volume.'),
    ('perform',12,'LEGS & LUNGS','[{"n":"Bodyweight Squat","sets":5,"reps":20},{"n":"Lunges Jump","sets":4,"reps":16},{"n":"Broad Jump","sets":4,"reps":10},{"n":"Single Leg Glutes Bridge","sets":3,"reps":15},{"n":"Wall Sit","sets":3,"reps":60},{"n":"Calf Raises","sets":4,"reps":25}]'::jsonb,45,'Advanced','None','Strength endurance in the legs.'),
    ('perform',13,'CORE & CARRY','[{"n":"Hollow Hold","sets":4,"reps":45},{"n":"Bicycle Crunch","sets":4,"reps":30},{"n":"Leg Raises","sets":4,"reps":15},{"n":"Bear Walk","sets":4,"reps":20},{"n":"Side Plank","sets":3,"reps":40},{"n":"Plank","sets":3,"reps":60}]'::jsonb,45,'Advanced','None','A midline that holds under fatigue.'),
    ('perform',15,'FULL BODY POWER','[{"n":"Squat Jump","sets":5,"reps":15},{"n":"Explosive Push Up","sets":5,"reps":10},{"n":"Bulgarian Split Squat","sets":5,"reps":12},{"n":"Bottle Bent Over Row","sets":5,"reps":14},{"n":"Plank Shoulder Taps","sets":4,"reps":24},{"n":"Hollow Hold","sets":4,"reps":45}]'::jsonb,50,'Advanced','Dumbbell (optional)','Move well, move fast, then move heavy.'),
    ('perform',16,'ENGINE','[{"n":"Burpee","sets":6,"reps":12},{"n":"Sprint On Spot","sets":6,"reps":30},{"n":"Mountain Climber","sets":6,"reps":40},{"n":"Tuck Jump","sets":5,"reps":12},{"n":"Skater Jump","sets":5,"reps":20}]'::jsonb,50,'Advanced','None','Conditioning. This one is supposed to hurt.'),
    ('perform',17,'PUSH & PULL','[{"n":"Push Up","sets":6,"reps":15},{"n":"Diamond Push Up","sets":5,"reps":12},{"n":"Decline Push Up","sets":5,"reps":12},{"n":"Bottle Bent Over Row","sets":5,"reps":15},{"n":"Bottle Shoulder Press","sets":5,"reps":12},{"n":"Tricep Dip Chair","sets":5,"reps":12}]'::jsonb,50,'Advanced','None','Upper body volume.'),
    ('perform',19,'LEGS & LUNGS','[{"n":"Bodyweight Squat","sets":6,"reps":20},{"n":"Lunges Jump","sets":5,"reps":16},{"n":"Broad Jump","sets":5,"reps":10},{"n":"Single Leg Glutes Bridge","sets":4,"reps":15},{"n":"Wall Sit","sets":4,"reps":60},{"n":"Calf Raises","sets":5,"reps":25}]'::jsonb,50,'Advanced','None','Strength endurance in the legs.'),
    ('perform',20,'CORE & CARRY','[{"n":"Hollow Hold","sets":5,"reps":45},{"n":"Bicycle Crunch","sets":5,"reps":30},{"n":"Leg Raises","sets":5,"reps":15},{"n":"Bear Walk","sets":5,"reps":20},{"n":"Side Plank","sets":4,"reps":40},{"n":"Plank","sets":4,"reps":60}]'::jsonb,50,'Advanced','None','A midline that holds under fatigue.'),
    ('perform',22,'FULL BODY POWER','[{"n":"Squat Jump","sets":5,"reps":15},{"n":"Explosive Push Up","sets":5,"reps":10},{"n":"Bulgarian Split Squat","sets":5,"reps":12},{"n":"Bottle Bent Over Row","sets":5,"reps":14},{"n":"Plank Shoulder Taps","sets":4,"reps":24},{"n":"Hollow Hold","sets":4,"reps":45}]'::jsonb,50,'Advanced','Dumbbell (optional)','Move well, move fast, then move heavy.'),
    ('perform',23,'ENGINE','[{"n":"Burpee","sets":6,"reps":12},{"n":"Sprint On Spot","sets":6,"reps":30},{"n":"Mountain Climber","sets":6,"reps":40},{"n":"Tuck Jump","sets":5,"reps":12},{"n":"Skater Jump","sets":5,"reps":20}]'::jsonb,50,'Advanced','None','Conditioning. This one is supposed to hurt.'),
    ('perform',24,'PUSH & PULL','[{"n":"Push Up","sets":6,"reps":15},{"n":"Diamond Push Up","sets":5,"reps":12},{"n":"Decline Push Up","sets":5,"reps":12},{"n":"Bottle Bent Over Row","sets":5,"reps":15},{"n":"Bottle Shoulder Press","sets":5,"reps":12},{"n":"Tricep Dip Chair","sets":5,"reps":12}]'::jsonb,50,'Advanced','None','Upper body volume.'),
    ('perform',26,'LEGS & LUNGS','[{"n":"Bodyweight Squat","sets":6,"reps":20},{"n":"Lunges Jump","sets":5,"reps":16},{"n":"Broad Jump","sets":5,"reps":10},{"n":"Single Leg Glutes Bridge","sets":4,"reps":15},{"n":"Wall Sit","sets":4,"reps":60},{"n":"Calf Raises","sets":5,"reps":25}]'::jsonb,50,'Advanced','None','Strength endurance in the legs.'),
    ('perform',27,'CORE & CARRY','[{"n":"Hollow Hold","sets":5,"reps":45},{"n":"Bicycle Crunch","sets":5,"reps":30},{"n":"Leg Raises","sets":5,"reps":15},{"n":"Bear Walk","sets":5,"reps":20},{"n":"Side Plank","sets":4,"reps":40},{"n":"Plank","sets":4,"reps":60}]'::jsonb,50,'Advanced','None','A midline that holds under fatigue.'),
    ('perform',29,'FULL BODY POWER','[{"n":"Squat Jump","sets":5,"reps":17},{"n":"Explosive Push Up","sets":5,"reps":12},{"n":"Bulgarian Split Squat","sets":5,"reps":14},{"n":"Bottle Bent Over Row","sets":5,"reps":16},{"n":"Plank Shoulder Taps","sets":4,"reps":28},{"n":"Hollow Hold","sets":4,"reps":52}]'::jsonb,50,'Advanced','Dumbbell (optional)','Move well, move fast, then move heavy.'),
    ('perform',30,'ENGINE','[{"n":"Burpee","sets":6,"reps":14},{"n":"Sprint On Spot","sets":6,"reps":34},{"n":"Mountain Climber","sets":6,"reps":46},{"n":"Tuck Jump","sets":5,"reps":14},{"n":"Skater Jump","sets":5,"reps":23}]'::jsonb,50,'Advanced','None','Conditioning. This one is supposed to hurt.'),
    ('perform',31,'PUSH & PULL','[{"n":"Push Up","sets":6,"reps":17},{"n":"Diamond Push Up","sets":5,"reps":14},{"n":"Decline Push Up","sets":5,"reps":14},{"n":"Bottle Bent Over Row","sets":5,"reps":17},{"n":"Bottle Shoulder Press","sets":5,"reps":14},{"n":"Tricep Dip Chair","sets":5,"reps":14}]'::jsonb,50,'Advanced','None','Upper body volume.'),
    ('perform',33,'LEGS & LUNGS','[{"n":"Bodyweight Squat","sets":6,"reps":23},{"n":"Lunges Jump","sets":5,"reps":18},{"n":"Broad Jump","sets":5,"reps":12},{"n":"Single Leg Glutes Bridge","sets":4,"reps":17},{"n":"Wall Sit","sets":4,"reps":69},{"n":"Calf Raises","sets":5,"reps":29}]'::jsonb,50,'Advanced','None','Strength endurance in the legs.'),
    ('perform',34,'CORE & CARRY','[{"n":"Hollow Hold","sets":5,"reps":52},{"n":"Bicycle Crunch","sets":5,"reps":34},{"n":"Leg Raises","sets":5,"reps":17},{"n":"Bear Walk","sets":5,"reps":23},{"n":"Side Plank","sets":4,"reps":46},{"n":"Plank","sets":4,"reps":69}]'::jsonb,50,'Advanced','None','A midline that holds under fatigue.'),
    ('perform',36,'FULL BODY POWER','[{"n":"Squat Jump","sets":5,"reps":17},{"n":"Explosive Push Up","sets":5,"reps":12},{"n":"Bulgarian Split Squat","sets":5,"reps":14},{"n":"Bottle Bent Over Row","sets":5,"reps":16},{"n":"Plank Shoulder Taps","sets":4,"reps":28},{"n":"Hollow Hold","sets":4,"reps":52}]'::jsonb,50,'Advanced','Dumbbell (optional)','Move well, move fast, then move heavy.'),
    ('perform',37,'ENGINE','[{"n":"Burpee","sets":6,"reps":14},{"n":"Sprint On Spot","sets":6,"reps":34},{"n":"Mountain Climber","sets":6,"reps":46},{"n":"Tuck Jump","sets":5,"reps":14},{"n":"Skater Jump","sets":5,"reps":23}]'::jsonb,50,'Advanced','None','Conditioning. This one is supposed to hurt.'),
    ('perform',38,'PUSH & PULL','[{"n":"Push Up","sets":6,"reps":17},{"n":"Diamond Push Up","sets":5,"reps":14},{"n":"Decline Push Up","sets":5,"reps":14},{"n":"Bottle Bent Over Row","sets":5,"reps":17},{"n":"Bottle Shoulder Press","sets":5,"reps":14},{"n":"Tricep Dip Chair","sets":5,"reps":14}]'::jsonb,50,'Advanced','None','Upper body volume.'),
    ('perform',40,'LEGS & LUNGS','[{"n":"Bodyweight Squat","sets":6,"reps":23},{"n":"Lunges Jump","sets":5,"reps":18},{"n":"Broad Jump","sets":5,"reps":12},{"n":"Single Leg Glutes Bridge","sets":4,"reps":17},{"n":"Wall Sit","sets":4,"reps":69},{"n":"Calf Raises","sets":5,"reps":29}]'::jsonb,50,'Advanced','None','Strength endurance in the legs.'),
    ('perform',41,'CORE & CARRY','[{"n":"Hollow Hold","sets":5,"reps":52},{"n":"Bicycle Crunch","sets":5,"reps":34},{"n":"Leg Raises","sets":5,"reps":17},{"n":"Bear Walk","sets":5,"reps":23},{"n":"Side Plank","sets":4,"reps":46},{"n":"Plank","sets":4,"reps":69}]'::jsonb,50,'Advanced','None','A midline that holds under fatigue.')
  ) as v(track, day_no, title, exercises, est_minutes, level, equipment, focus)
 where c.slug = 't42-nov-2026'
on conflict (challenge_id, track, day_no) do update set
  title       = excluded.title,
  exercises   = excluded.exercises,
  est_minutes = excluded.est_minutes,
  level       = excluded.level,
  equipment   = excluded.equipment,
  focus       = excluded.focus;

-- Check it landed: 18 START, 24 TRANSFORM, 30 PERFORM.
--
--   select track, count(*) from public.t42_plan_days
--     join public.t42_challenges c on c.id = challenge_id
--    where c.slug = 't42-nov-2026' group by track order by track;
